[project]
name = "prisoner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = ["black", "mypy"]

[project.scripts]
prisoner = "prisoner.main:main"